### ISSUE TITLE
Bootstrap & Front End Responsive Frameworks Research 

### ISSUE THREAD

**Issue by tawana0518** [tawana0518/mywebclass-simulation#13]
- Research Front End Responsive Frameworks and Bootstrap.
- Understand Current Implementation of Bootstrap in MyWebClass.
- Create a Wiki Page on the research which includes the improvements recommendations for MyWebClass.

**Comment by rk864** [comment]
Based on the  project structure, Bootstrap is already implemented and being used for styling myWebClass website. Here's a brief explanation of the current implementation and some minimal improvements we can make in Sprint1.

- **Bootstrap CSS**: In scss/styles.scss file, we're importing Bootstrap's SCSS files. This means we're using the source files of Bootstrap, which allows us to customize the default styles and utilize Bootstrap's mixins and variables.

- **Bootstrap JavaScript**: In your src/js/main.js file, you're importing Bootstrap's JavaScript components. These components are responsible for adding interactivity to your website, like modals, dropdowns, and more.

### **To understand the current implementation, you can start by exploring the following:**

1. **HTML Structure**: Review the index.html file to see how Bootstrap's grid system and utility classes are being used to create a responsive layout.

2. **SCSS Customization**: Check the scss/styles.scss file to see how the project imports Bootstrap's SCSS files and how you can customize the default styles.

3. **JavaScript Components**: Look into the src/js/main.js file to see how Bootstrap's JavaScript components are being imported and initialized.

### **Some minimal improvements we can make within first Sprint:**

- Improve Accessibility: Ensure that your website follows accessibility best practices. Add aria-* attributes, use semantic HTML tags, and ensure proper keyboard navigation.
- Optimize Images: Compress images to reduce their file size, which will result in faster page load times. You can use online tools like [TinyPNG](https://tinypng.com/) or [ImageOptim](https://imageoptim.com/) for this task.
- Customize Bootstrap: Update the scss/styles.scss file to customize Bootstrap's default styles. You can change colors, fonts, and other visual elements by overriding Bootstrap's variables or adding your own CSS rules.
- Update Bootstrap Components: If you're using any deprecated or older Bootstrap components, update them to use the latest version of the components.
- Mobile-First Approach: Review your website on smaller screens (mobile devices) and ensure the layout and user experience are optimized for those devices. Make any necessary adjustments to improve the mobile experience.

Remember to test our changes on different devices and screen sizes to ensure the improvements work as expected.
