### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by bmarani** [tawana0518/mywebclass-simulation#2]
Enhancements in Sprint1:

1. Updated the lang attribute in the html tag to support dynamic language changes.
2. Optimized the title and meta description for SEO.
3. Added descriptive text for the navbar toggle button.
4. Enabled the "Start Here" button for users to land on the "start_here" html page.
5. Added better descriptive text for the teacher-students image.
6. Updated the Privacy link text to "Privacy and Cookies Policy".
7. Added labels to associate the form input with its purpose.

**Comment by rk864** [comment]
@bmarani @tawana0518  - Please review the issue and feel free to add/correct. we will discuss it further when we meet later evening today. thank you!

**Comment by rk864** [comment]
Enhancements in Sprint1
1. there is a "start_here" button in the index.html file while is not enabled. Enable the button to land in Start here page. 
div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3"
    button type="button" class="btn btn-success btn-lg px-4 me-md-2 fw-bold">Start
2. Create basic template for the "start_here.html" page, which includes the same header, navigation, and footer sections as the "index.html" file. In coming Sprints, We will further customize the content within the <main> section as per our requirements.
