### ISSUE TITLE
SEO Research

### ISSUE THREAD

**Issue by bmarani** [tawana0518/mywebclass-simulation#5]
Summary of SEO:

SEO: Search Engine Optimization, the process of optimizing a website to improve its visibility and ranking on search engine results pages (SERPs) with the goal of increasing organic traffic.

Business requirement for SEO: Improve website visibility and ranking to attract more traffic, generate leads, increase revenue, establish a positive online reputation, and build trust with customers.

SEO implementation and testing: Playwright tests and Lighthouse reports can be used together to test and optimize a website's SEO. Playwright tests simulate user interactions to test website functionality, while Lighthouse generates reports on performance, accessibility, best practices, and SEO. Together, they help ensure that a website meets SEO best practices and is optimized for search engines, improving visibility and organic traffic.

**Comment by tawana0518** [comment]
Research completed. SEO documentation has been added to the Wiki.

**Comment by tawana0518** [comment]
Summary of SEO: 

SEO: Search Engine Optimization, the process of optimizing a website to improve its visibility and ranking on search engine results pages (SERPs) with the goal of increasing organic traffic.

Business requirement for SEO: Improve website visibility and ranking to attract more traffic, generate leads, increase revenue, establish a positive online reputation, and build trust with customers.

SEO implementation and testing: Utilize tools and technologies such as SEO auditing tools, keyword research tools, analytics tools, CMS platforms, web development frameworks, and browser extensions to ensure proper SEO implementation, conduct positive and negative tests, and optimize website elements.

**Comment by tawana0518** [comment]
Issue reopened - looking into playwright tests scripts

**Comment by tawana0518** [comment]
For the webpage to pass SEO requirements, it must contain the following basic SEO practices: 

Keyword research
Meta tags
URL structure
Mobile-friendliness
Fast load times

**Comment by tawana0518** [comment]
Playwright Test script to test the above in the webpages: 

const { chromium } = require('playwright');

const PAGE_URL = 'http://localhost:3000';
const PAGE_LOAD_TIMEOUT = 60000;
const MOBILE_VIEWPORT = { width: 375, height: 667 };

const playwrightTest = async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: MOBILE_VIEWPORT,
    userAgent: 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19',
  });
  const page = await context.newPage();
  
  await page.goto(PAGE_URL, { timeout: PAGE_LOAD_TIMEOUT });

  // Test for keyword research
  const keywords = ['keyword1', 'keyword2', 'keyword3'];
  const pageContent = await page.textContent('body');
  const hasKeywords = keywords.every(keyword => pageContent.includes(keyword));
  console.log(`Keyword Research Test: ${hasKeywords ? 'Passed' : 'Failed'}`);

  // Test for meta tags
  const pageTitle = await page.title();
  const pageMetaDescription = await page.$eval('meta[name="description"]', el => el.content);
  const hasMetaTags = Boolean(pageTitle && pageMetaDescription);
  console.log(`Meta Tags Test: ${hasMetaTags ? 'Passed' : 'Failed'}`);

  // Test for URL structure
  const pageUrl = page.url();
  const pageUrlPathname = new URL(pageUrl).pathname;
  const hasProperUrlStructure = Boolean(pageUrl && !pageUrl.includes('%20') && !pageUrlPathname.includes('//'));
  console.log(`URL Structure Test: ${hasProperUrlStructure ? 'Passed' : 'Failed'}`);

  // Test for mobile-friendliness
  const isMobileFriendly = page.viewportSize().width < 768;
  console.log(`Mobile-Friendliness Test: ${isMobileFriendly ? 'Passed' : 'Failed'}`);

  // Test for fast load times
  const pageLoadTime = await page.evaluate(() => window.performance.timing.domContentLoadedEventEnd - window.performance.timing.navigationStart);
  const isFastLoading = pageLoadTime <= 3000;
  console.log(`Fast Load Times Test: ${isFastLoading ? 'Passed' : 'Failed'}`);

  await browser.close();
};

playwrightTest();



To be broken down and tested across homepage, 3 content pages once framework is in place.

**Comment by tawana0518** [comment]
Fixed Playwright Test Script for SEO research -- will be including mobile friendliness in next test run once Bootstrap frame work has been added into HTML framework. 

import { test, expect } from '@playwright/test'

test.describe('MyWebClass.org tests', () => {
  test('SEO tests', async ({ page }) => {
    await page.goto('http://localhost:3000/')
    // Test for keyword research
    const keywords = ['MyWebClass.org']
    const pageContent = await page.textContent('body')
    const hasKeywords = keywords.every(keyword => pageContent.includes(keyword))
    expect(hasKeywords).toBeTruthy()
    // Test for meta tags
    const pageTitle = await page.title()
    const pageMetaDescription = await page.$eval('meta[name="description"]', el => el.content)
    const pageMetaKeywords = await page.$eval('meta[name="keywords"]', el => el.content)
    const hasMetaTags = Boolean(pageTitle && pageMetaDescription && pageMetaKeywords)
    expect(hasMetaTags).toBeTruthy()
    // Test for URL structure
    const pageUrl = page.url()
    const pageUrlPathname = new URL(pageUrl).pathname
    const hasProperUrlStructure = Boolean(pageUrl && !pageUrl.includes('%20') && pageUrlPathname === '/')
    expect(hasProperUrlStructure).toBeTruthy()
    // Test for fast load times
    const pageLoadTime = await page.evaluate(() => window.performance.timing.domContentLoadedEventEnd - window.performance.timing.navigationStart)
    const isFastLoading = pageLoadTime <= 3000
    expect(isFastLoading).toBeTruthy()
  })
})

Code to be added once Bootstrap has been implemented:

 // Test for mobile-friendliness
    console.log(page.viewportSize().width)
    const isMobileFriendly = page.viewportSize().width < 768
    expect(isMobileFriendly).toBeTruthy()

**Comment by tawana0518** [comment]
Sprint 1 will not include mobile friendliness -- will begin working on that in sprint 2
